title: "selfdriven Tel"
description: "Telecommunication Network Services"
baseurl: ""
url: ""
context: "tel"
repo: "selfdriven-services/selfdriven-tel"
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: default
plugins:
  - jekyll-feed
  - jekyll-seo-tag
